### PR TITLE
Javascript fixes for Hidden Content on Pageload

### PR DESCRIPTION
**Pull request by ethanbeyer**

### CODE REVIEW

**Comment by ethanbeyer** [comment]
Hey @outflux3 - I hope this wasn't viewed in any way as me looking to step on your toes!

I saw that you updated to 1.0.3 but I also introduced a few other little features, like `data-simplemde-made` to prevent running on fields that had already been instantiated (in my tests there was no need to reinit a field that had been previously visible), as well as the check to see whether or not the field was visible.

These tiny changes made it just that bit more dependable and quick. Thought I would drop you a line about this pull request to see if you would consider merging my changes into the main branch.

Thanks!!

**Comment by outflux3** [comment]
ok sure - no problem, sorry i didn't notice all of your changes, i couldn't accept the pull request because of some conflicting stuff and then the js file was too big so it was asking me to go to the command line; i will try again, else we may need to separate out the assets and include the whole SimpleMDE package, which will make upgrading it easier and also smaller filesize on the js file

**Comment by outflux3** [comment]
i basically have no clue how to do what they are asking on this checkout via command line, i looked in github app but do not see any command line interface

**Comment by ethanbeyer** [comment]
I use sourcetree (check it out, it is INCREDIBLE)!

I will pull your changes into mine, fix the conflicts and re-submit this pull request 💃

**Comment by outflux3** [comment]
it's ok i figured it out and it's all good now.

**Comment by outflux3** [comment]
now i have no clue how i ended up with a branch and i don't need it i need to get the branch to be the master, this is super annoying, sorry

**Comment by ethanbeyer** [comment]
lol dangit I didn't see that! Aghhh

**Comment by ethanbeyer** [comment]
do you need any help?

**Comment by outflux3** [comment]
somehow the pr/2 is the one where i just did all the work, it's all there done, now needs to somehow get put to master and delete that branch

**Comment by ethanbeyer** [comment]
ok so the thing you need to do is to merge `pr/2` into `master` and then delete `pr/2`

**Pull request closed without merging**
